name: self_introduction_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  rive: ^0.13.20
  get_it: ^8.0.3
  injectable: ^2.5.0
  injectable_generator: ^2.7.0
  build_runner: ^2.4.14
  flutter_bloc: ^9.0.0
  freezed: ^2.5.2
  freezed_annotation: ^2.4.4
  responsive_framework: ^1.5.1
  visibility_detector: ^0.4.0+2
  universal_html: ^2.2.4
  google_fonts: ^6.2.1
  universal_platform: ^1.1.0
  flutter_svg: ^2.1.0
  xml: ^6.5.0
  
  
  
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/Images/
    - assets/rive/




