import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';
import 'package:go_router/go_router.dart';
import 'package:self_introduction_flutter/page/tech_blog_page/tech_blog_cubit.dart';
import 'package:self_introduction_flutter/page/tech_blog_page/tech_blog_desktop/widget/tech_post_title.dart';
import 'package:self_introduction_flutter/page/tech_blog_page/tech_blog_state.dart';

class AllPostsList extends StatelessWidget {
  const AllPostsList({super.key});

  @override
  Widget build(BuildContext context) {
    return BlocBuilder<TechBlogCubit, TechBlogState>(
      builder: (context, state) {
        final cubit = context.read<TechBlogCubit>();

        return SizedBox(
          width: 600,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              TechPostTitle(
                isUpload: true,
                number: 1,
                title: 'MVVM',
                tags: '#MVVM  #ViewModel  #Model',
                onTap: () => context.go('/tech-blog/post/mvvm'),
                onHover: (title) => cubit.onPostHover(title),
                onHoverExit: () => cubit.onPostHoverExit(),
              ),
              const SizedBox(height: 40),
              TechPostTitle(
                isUpload: true,
                number: 2,
                title: 'Clean Architecture',
                tags:
                    '#Clean Architecture  #Domain  #Presentation  #Repository pattern',
                onTap: () => context.go('/tech-blog/post/clean-architecture'),
                onHover: (title) => cubit.onPostHover(title),
                onHoverExit: () => cubit.onPostHoverExit(),
              ),
              const SizedBox(height: 40),
              TechPostTitle(
                isUpload: true,
                number: 3,
                title: 'Repository Pattern',
                tags: '#Repository  #Data Layer  #API',
                onTap: () => context.go('/tech-blog/post/repository-pattern'),
                onHover: (title) => cubit.onPostHover(title),
                onHoverExit: () => cubit.onPostHoverExit(),
              ),
              const SizedBox(height: 40),
              TechPostTitle(
                isUpload: true,
                number: 4,
                title: 'BLoC / Cubit',
                tags: '#BLoC  #Cubit  #State Management',
                onTap: () => context.go('/tech-blog/post/bloc-cubit'),
                onHover: (title) => cubit.onPostHover(title),
                onHoverExit: () => cubit.onPostHoverExit(),
              ),
              const SizedBox(height: 40),
              TechPostTitle(
                isUpload: true,
                number: 5,
                title: 'Provider (단점만 모아보기?)',
                tags: '#Provider  #State Management  #Context',
                onTap: () => context.go('/tech-blog/post/provider'),
                onHover: (title) => cubit.onPostHover(title),
                onHoverExit: () => cubit.onPostHoverExit(),
              ),
              const SizedBox(height: 40),
              TechPostTitle(
                isUpload: true,
                number: 6,
                title: 'Dependency Injection (GetIt + Injectable)',
                tags: '#GetIt  #Injectable  #DI',
                onTap: () => context.go('/tech-blog/post/dependency-injection'),
                onHover: (title) => cubit.onPostHover(title),
                onHoverExit: () => cubit.onPostHoverExit(),
              ),
              const SizedBox(height: 40),
              TechPostTitle(
                isUpload: true,
                number: 7,
                title: 'Freezed',
                tags: '#Freezed  #Immutable  #Code Generation',
                onTap: () => context.go('/tech-blog/post/freezed'),
                onHover: (title) => cubit.onPostHover(title),
                onHoverExit: () => cubit.onPostHoverExit(),
              ),
              const SizedBox(height: 40),
              TechPostTitle(
                isUpload: true,
                number: 8,
                title: 'json_serializable\njson_annotation 자동 JSON 직렬화',
                tags: '#json_serializable  #json_annotation  #Serialization',
                onTap: () => context.go('/tech-blog/post/json-serializable'),
                onHover: (title) => cubit.onPostHover(title),
                onHoverExit: () => cubit.onPostHoverExit(),
              ),
              const SizedBox(height: 40),
              TechPostTitle(
                isUpload: true,
                number: 9,
                title: 'Isar 로컬 NoSQL DB',
                tags: '#Isar  #NoSQL  #Local Database',
                onTap: () => context.go('/tech-blog/post/isar'),
              ),
              const SizedBox(height: 40),
              TechPostTitle(
                isUpload: true,
                number: 10,
                title: 'SharedPreferences\nFlutter Secure Storage 로컬 캐싱',
                tags: '#SharedPreferences  #SecureStorage  #Local Cache',
                onTap: () => context.go('/tech-blog/post/local-storage'),
              ),
              const SizedBox(height: 40),
              TechPostTitle(
                isUpload: true,
                number: 11,
                title: 'MemoryCache\nDio Cache Interceptor - 메모리 및 네트워크 캐싱',
                tags: '#MemoryCache  #Dio  #Network Cache',
                onTap: () => context.go('/tech-blog/post/memory-cache'),
              ),
              const SizedBox(height: 40),
              TechPostTitle(
                number: 12,
                title: '네이버 로그인',
                tags: '#Naver  #Login  #OAuth  #Social Login',
                onTap: () => context.go('/schedule'),
                uploadDate: '6월 25일',
              ),
              const SizedBox(height: 40),
              TechPostTitle(
                number: 13,
                title: '카카오 로그인',
                tags: '#Kakao  #Login  #OAuth  #Social Login',
                onTap: () => context.go('/schedule'),
                uploadDate: '6월 25일',
              ),
              const SizedBox(height: 40),
              TechPostTitle(
                number: 14,
                title: '화면 전환 (네비게이터)',
                tags: '#Navigator  #Routing  #Screen Transition',
                onTap: () => context.go('/schedule'),
                uploadDate: '6월 28일',
              ),
              const SizedBox(height: 40),
              TechPostTitle(
                number: 15,
                title: 'Flutter 밑줄 선 (한글에서 안깨지는 방법)',
                tags: '#Underline  #Korean  #Text Decoration',
                onTap: () => context.go('/schedule'),
                uploadDate: '6월 28일',
              ),
              const SizedBox(height: 40),
              TechPostTitle(
                number: 16,
                title: '배경화면 블러처리, 패딩 제거',
                tags: '#Blur  #Background  #Padding  #UI',
                onTap: () => context.go('/schedule'),
                uploadDate: '6월 28일',
              ),
              const SizedBox(height: 40),
              TechPostTitle(
                number: 17,
                title: '네트워크 이미지 사용방법 (심화 x, 기초)',
                tags: '#Network Image  #HTTP  #Image Loading',
                onTap: () => context.go('/schedule'),
                uploadDate: '6월 28일',
              ),
              const SizedBox(height: 40),
              TechPostTitle(
                number: 18,
                title: '카카오 맵 사용방법',
                tags: '#Kakao Map  #Map  #Location  #API',
                onTap: () => context.go('/schedule'),
                uploadDate: '7월 2일',
              ),
              const SizedBox(height: 40),
              TechPostTitle(
                number: 19,
                title: '자동 스크롤 (글로벌키, 고정 스크롤)',
                tags: '#Auto Scroll  #GlobalKey  #ScrollController',
                onTap: () => context.go('/schedule'),
                uploadDate: '7월 2일',
              ),
              const SizedBox(height: 40),
              TechPostTitle(
                number: 20,
                title: '다이아로그 함수 (Page-view)',
                tags: '#Dialog  #PageView  #Modal  #Popup',
                onTap: () => context.go('/schedule'),
                uploadDate: '7월 2일',
              ),
              const SizedBox(height: 40),
              TechPostTitle(
                number: 21,
                title: '랜덤 함수',
                tags: '#Random  #Math  #Utilities',
                onTap: () => context.go('/schedule'),
                uploadDate: '7월 2일',
              ),
              const SizedBox(height: 40),
              TechPostTitle(
                number: 22,
                title: '부모 위젯 사이즈 설정(x) 자식이 따라가기',
                tags: '#Widget Size  #Parent Child  #Layout',
                onTap: () => context.go('/schedule'),
                uploadDate: '7월 2일',
              ),
              const SizedBox(height: 40),
              TechPostTitle(
                number: 23,
                title: '부모위젯 최소 자유 최대 x',
                tags: '#Constraints  #Min Max  #Flexible  #Layout',
                onTap: () => context.go('/schedule'),
                uploadDate: '7월 2일',
              ),
              const SizedBox(height: 40),
              TechPostTitle(
                number: 24,
                title: '서버와 연결 (쿠키, secure_storage, dio)',
                tags: '#Server  #Cookie  #Dio  #HTTP',
                onTap: () => context.go('/schedule'),
                uploadDate: '7월 2일',
              ),
              const SizedBox(height: 40),
              TechPostTitle(
                number: 25,
                title: 'Flutter 생명주기 정리',
                tags: '#Lifecycle  #StatefulWidget  #App Lifecycle',
                onTap: () => context.go('/schedule'),
                uploadDate: '7월 7일',
              ),
              const SizedBox(height: 40),
              TechPostTitle(
                number: 26,
                title: '서버 데이터 가공 연습',
                tags: '#Data Processing  #JSON  #API Response',
                onTap: () => context.go('/schedule'),
                uploadDate: '7월 7일',
              ),
              const SizedBox(height: 40),
              TechPostTitle(
                number: 27,
                title: '스크롤 관련',
                tags: '#Scroll  #ScrollView  #ScrollController',
                onTap: () => context.go('/schedule'),
                uploadDate: '7월 7일',
              ),
              const SizedBox(height: 40),
              TechPostTitle(
                number: 28,
                title: 'FutureBuilder',
                tags: '#FutureBuilder  #Async  #Future',
                onTap: () => context.go('/schedule'),
                uploadDate: '7월 7일',
              ),
              const SizedBox(height: 40),
              TechPostTitle(
                number: 29,
                title: '바텀 모달시트',
                tags: '#BottomSheet  #Modal  #showModalBottomSheet',
                onTap: () => context.go('/schedule'),
                uploadDate: '7월 7일',
              ),
              const SizedBox(height: 40),
              TechPostTitle(
                number: 30,
                title: '드롭다운 버튼',
                tags: '#DropdownButton  #Dropdown  #Selection',
                onTap: () => context.go('/schedule'),
                uploadDate: '7월 7일',
              ),
              const SizedBox(height: 40),
              TechPostTitle(
                number: 31,
                title: '날짜 변환',
                tags: '#DateTime  #DateFormat  #Date Conversion',
                onTap: () => context.go('/schedule'),
                uploadDate: '7월 7일',
              ),
              const SizedBox(height: 40),
              TechPostTitle(
                number: 32,
                title: '하이브 로컬 저장',
                tags: '#Hive  #Local Storage  #NoSQL',
                onTap: () => context.go('/schedule'),
                uploadDate: '7월 7일',
              ),
              const SizedBox(height: 40),
              TechPostTitle(
                number: 33,
                title: '다이나믹 아일랜드',
                tags: '#Dynamic Island  #iOS  #UI Feature',
                onTap: () => context.go('/schedule'),
                uploadDate: '7월 10일',
              ),
              const SizedBox(height: 40),
              TechPostTitle(
                number: 34,
                title: '아이콘 클릭 이벤트 애니메이션',
                tags: '#Icon Animation  #Click Event  #Animation',
                onTap: () => context.go('/schedule'),
                uploadDate: '7월 10일',
              ),
              const SizedBox(height: 40),
              TechPostTitle(
                number: 35,
                title: 'Flutter 화면 스크롤 감지',
                tags:
                    '#Scroll Detection  #NotificationListener  #ScrollNotification',
                onTap: () => context.go('/schedule'),
                uploadDate: '7월 10일',
              ),
              const SizedBox(height: 40),
              TechPostTitle(
                number: 36,
                title: 'PopupMenuButton',
                tags: '#PopupMenuButton  #Menu  #Popup',
                onTap: () => context.go('/schedule'),
                uploadDate: '7월 10일',
              ),
              const SizedBox(height: 40),
              TechPostTitle(
                number: 37,
                title: 'CachedNetworkImage',
                tags: '#CachedNetworkImage  #Image Cache  #Network Image',
                onTap: () => context.go('/schedule'),
                uploadDate: '7월 10일',
              ),
              const SizedBox(height: 40),
              TechPostTitle(
                number: 38,
                title: 'dio 캐시 처리',
                tags: '#Dio  #Cache  #HTTP Cache  #Interceptor',
                onTap: () => context.go('/schedule'),
                uploadDate: '7월 10일',
              ),
              const SizedBox(height: 40),
              TechPostTitle(
                number: 39,
                title: '캘린더 라이브러리',
                tags: '#Calendar  #Date Picker  #Library',
                onTap: () => context.go('/schedule'),
                uploadDate: '7월 10일',
              ),
              const SizedBox(height: 40),
              TechPostTitle(
                number: 40,
                title: 'NaverMap with Flutter',
                tags: '#Naver Map  #Map Widget  #Location',
                onTap: () => context.go('/schedule'),
                uploadDate: '7월 10일',
              ),
              const SizedBox(height: 40),
              TechPostTitle(
                number: 41,
                title: '바텀 네비게이션 바 (구글)',
                tags: '#BottomNavigationBar  #Navigation  #Google Style',
                onTap: () => context.go('/schedule'),
                uploadDate: '7월 10일',
              ),
              const SizedBox(height: 40),
              TechPostTitle(
                number: 42,
                title: '물결 애니메이션',
                tags: '#Wave Animation  #Custom Animation  #Ripple',
                onTap: () => context.go('/schedule'),
                uploadDate: '7월 10일',
              ),
              const SizedBox(height: 40),
              TechPostTitle(
                number: 43,
                title: '그라디언트',
                tags: '#Gradient  #LinearGradient  #RadialGradient',
                onTap: () => context.go('/schedule'),
                uploadDate: '7월 13일',
              ),
              const SizedBox(height: 40),
              TechPostTitle(
                number: 44,
                title: '⭐ 반짝이는 별 애니메이션 구현 기록',
                tags: '#Star Animation  #Sparkle  #Custom Animation',
                onTap: () => context.go('/schedule'),
                uploadDate: '7월 13일',
              ),
            ],
          ),
        );
      },
    );
  }
}
