final List<Map<String, dynamic>> libraryData = [
  {
    'title': '기능별 외부 API 및 SDK 연동',
    'description': '로그인, 지도, 위치, 인증 등 외부 서비스와 직접 연동되는 패키지',
    'imagePath': 'assets/Images/ifsai_img/lb_1.png',
    'libraries': [
      'flutter_naver_login',
      'kakao_flutter_sdk',
      'google_sign_in',
      'flutter_secure_storage',
      'flutter_jailbreak_detection',
      'url_launcher',
      'kakao_map_plugin',
      'geolocator',
      'flutter_naver_map',
      'permission_handler',
      'flutter_compass',
    ],
  },
  {
    'title': '앱 내부 구조 및 아키텍처 관련',
    'description': '앱 구성, 의존성 주입, 상태 관리, DB, 캐시 등 구조 설계 관련',
    'imagePath': 'assets/Images/ifsai_img/lb_2.png',
    'libraries': [
      'provider',
      'get',
      'flutter_bloc',
      'isar',
      'isar_flutter_libs',
      'shared_preferences',
      'dio',
      'dio_cache_interceptor',
      'cookie_jar',
      'dio_cookie_manager',
      'flutter_dotenv',
      'freezed_annotation',
      'build_runner',
      'freezed',
      'injectable',
      'injectable_generator',
      'json_annotation',
      'get_it',
      'path_provider',
    ],
  },
  {
    'title': 'UI/UX 및 애니메이션, 기타 뷰 요소',
    'description': '화면 구성, 애니메이션, 뷰 전환 등 사용자 경험 관련 요소',
    'imagePath': 'assets/Images/ifsai_img/lb_3.png',
    'libraries': [
      'cupertino_icons',
      'rive',
      'smooth_page_indicator',
      'intl',
      'shimmer',
      'cached_network_image',
      'custom_rating_bar',
      'expandable_text',
      'flutter_animate',
      'image_picker',
      'custom_refresh_indicator',
      'flutter_svg',
      'sliding_up_panel',
    ],
  },
];
